# Generated by Django 2.2.2 on 2019-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial_squashed_0023_usernode_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermember',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
