# Generated by Django 2.2.2 on 2019-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servermember_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
