# Generated by Django 2.2.2 on 2019-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usernode_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=256)),
                ('type', models.CharField(choices=[('mn', 'Masternode'), ('pool', 'Pool')], db_index=True, max_length=16)),
            ],
        ),
    ]
