# Generated by Django 2.2.2 on 2019-08-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skippedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='unstaking',
            name='fulfill_at',
            field=models.DateTimeField(null=True),
        ),
    ]
