# Generated by Django 2.2.2 on 2019-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_unstaking_fulfill_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkippedTransaction',
        ),
        migrations.AlterField(
            model_name='servermember',
            name='_dm_channel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='DM channel ID'),
        ),
    ]
