# Generated by Django 2.2.2 on 2019-08-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlog',
            name='is_sell',
            field=models.BooleanField(default=True),
        ),
    ]
