# Generated by Django 2.2.2 on 2019-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_orderlog_is_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermember',
            name='is_staking_pool',
            field=models.BooleanField(default=True),
        ),
    ]
