# Generated by Django 2.2.2 on 2019-11-01 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_updateroletask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasternodeBalanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=8, max_digits=32)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=32)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ServerMember')),
            ],
        ),
    ]
