# Generated by Django 2.2.2 on 2019-11-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mninvesttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermember',
            name='last_forced_activity_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
