# Generated by Django 2.2.2 on 2019-12-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191125_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermember',
            name='noinform',
            field=models.BooleanField(default=False),
        ),
    ]
