# Generated by Django 2.2.2 on 2020-01-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_tgraintask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedMasternode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=64)),
                ('outidx', models.SmallIntegerField()),
                ('last_check_status', models.CharField(max_length=32)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_masternodes', to='app.ServerMember')),
            ],
        ),
    ]
