# Generated by Django 2.2.2 on 2020-01-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200121_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedmasternode',
            name='outidx',
        ),
    ]
