# Generated by Django 2.2.2 on 2020-06-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_trackedmasternode_outidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgraintask',
            name='_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
