# Generated by Django 2.2.2 on 2020-06-29 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_tgraintask__chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ServerMember')),
            ],
        ),
    ]
