# Generated by Django 2.2.2 on 2020-09-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_airdroptask_is_rain'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermember',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
